### ISSUE TITLE
What is changed between version 0.7.6 and 0.7.7?

### ISSUE THREAD

**Issue by Tolsi** [sebastien/cuisine#188]
I can't find any changelog and our code stopped working correctly after upgrade to 0.7.7. It also does not work on 0.7.9.

```
$ sudo pip install cuisine==0.7.6
$ fab config.prod start
[...] Executing task 'start'
[...] sudo: service service1 start ; true
...
Done.
$ sudo pip install cuisine==0.7.7
$ fab config.prod start
[...] Executing task 'start'
ERROR:root:service1: unrecognized service
```
like it executes locally, not on remote machine

**Comment by Slach** [comment]
you can use workaround

import cuisine
cuisine.mode_remote()

**Comment by Tolsi** [comment]
It seems that it works. But what about backwards compatibility? It is not decent, especially since there is no documentation for the update to the new version.

**Comment by Slach** [comment]
Sergey, i'm not mantainer of this package ;) i just subscribe to github issues and have same problem

**Comment by sebastien** [comment]
Hi Sergey,

Do you have a test case that execises the regression between 0.7.6 and 0.7.7? The culprit is likely to be these lines:

```
	# If we don't find a host, we setup the local mode
	if not fabric.api.env.host_string: mode_local()
```
I've removed it from 0.7.10 -- let me know how it goes. If it still doesn't work, please make a test-case and I'll investigate.

**Comment by Tolsi** [comment]
0.7.10 works without any code changes. So, this is the right behavior?

**Comment by sebastien** [comment]
Great, you're welcome to contribute a test case if you're worried about regressions.
