### ISSUE TITLE
`dir_ensure` tries to create the directory even if it exists

### ISSUE THREAD

**Issue by jaapz** [sebastien/cuisine#194]
When i try to ensure that a directory exists, cuisine always tries to create it, even if it exists.

If I change the `echo OK` to `echo -n OK` (forcing echo to not output a newline) everything works like it should.

Looks like `endswith('OK')` does not return True when the returned value ends with a newline.

**Comment by sebastien** [comment]
Thanks, done!

**Comment by jaapz** [comment]
@sebastien thanks for the quick fix!

**Comment by sebastien** [comment]
My pleasure :) thanks for letting me know!
