### ISSUE TITLE
Please rename "bsd" features "freebsd"

### ISSUE THREAD

**Issue by ahpnils** [sebastien/cuisine#197]
Some features have a "bsd" suffix or prefix, but can only be used with FreeBSD. Using "bsd" can lead to errors on some BSD systems : for example, NetBSD does not have a "pw" utility for groups and users, but does have "useradd" and "groupadd".

I know this change of naming scheme is not backwards compatible, so I'm opening this issue to start debating on how adding BSD systems support could be done.

**Comment by sebastien** [comment]
Hi Nils,

I think that we could simply mention that `bsd` means FreeBSD and that the other BSDs would be `netbsd`, `openbsd` and so forth. That would save from backward-compatiblity breakages.

**Comment by ahpnils** [comment]
I understand the "no backward-compatiblity breakage" policy. Thanks for your answer !
