### ISSUE TITLE
package_ensure_apt(package_name, update=True) upgrade all package not only selected

### ISSUE THREAD

**Issue by Slach** [sebastien/cuisine#200]
need replace 
apt-get upgrade <package> 
to 
apt-get install --only-upgrade <package>
in package_update_apt

**Comment by sebastien** [comment]
Let me know if this works for you.

**Comment by Slach** [comment]
yes it's works for me 
i get this receipt from 
http://askubuntu.com/questions/44122/how-to-upgrade-a-single-package-using-apt-get
